### ISSUE TITLE
link in demo is broken

### ISSUE THREAD

**Issue by smichea** [andreasbm/focus-trap#2]
Hi Andreas,

in your demo, https://appnest-demo.firebaseapp.com/focus-trap/ the link 
`<a href="http://forums.devshed.com/html-programming-1/safari-submit-button-wont-focus-tab-key-effectively-488012.html" target="_blank">here</a>`
seems broken.

Congratulations for your work!

**Comment by andreasbm** [comment]
Hi Sebastien!

Thanks a lot opening this issue and notifying me about the broken link in the demo 👍I have found another article and changed the link in the demo.

Have a great day! ☀️
